version: "3.2"
services:
  flask:
    build: .
    restart: always
    environment:
      - APP_NAME=flask
    expose:
      - 8080
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - ./public_html/:/usr/local/apache2/htdocs/
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
